apiVersion: v2
appVersion: 0.17.2
description: A Helm chart for NACK
icon: https://nats.io/img/nats-icon-color.png
keywords:
- nats
- jetstream
- cncf
maintainers:
- email: info@nats.io
  name: The NATS Authors
  url: https://github.com/nats-io
name: nack
version: 0.28.1
