replicaCount: 1
version: 1
name: passit-front
environment: development

deployment:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  image:
    url: ncostamagna/passit-front
    version: "4c9b953f1a6d8ca20df3e1ebd90febb0c4a5e3ca"
    pullPolicy: IfNotPresent
  serviceType: ClusterIP

config:
  port: 3000
  baseUrl: "https://passit.ncostamagna.com"
  grpcHost: "passit-back.axul.svc.cluster.local:8050"

gateway:
  host: "passit.ncostamagna.com"

