replicaCount: 1
version: 1
name: passit-front
environment: development

deployment:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  image:
    url: ncostamagna/passit-front
    version: "57eef8c775b5f1f9f5888e5decb8a8ecbe0da8a3"
    pullPolicy: IfNotPresent
  serviceType: ClusterIP

config:
  port: 3000
  baseUrl: "https://passit.ncostamagna.com"
  grpcHost: "passit-back.axul.svc.cluster.local:8050"

gateway:
  host: "passit.ncostamagna.com"

