replicaCount: 1
version: 1
name: passit-front
environment: development

deployment:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  image:
    url: ncostamagna/passit-front
    version: "483fe1046c7804f6c35c24c3bf737db5471b93e7"
    pullPolicy: IfNotPresent
  serviceType: ClusterIP

config:
  port: 3000
  baseUrl: "https://passit.127.0.0.1.nip.io"
  grpcHost: "passit-back.axul.svc.cluster.local:8050"

gateway:
  host: "passit.127.0.0.1.nip.io"
  tlsSecret: "passit-front-tls"