apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ .Values.name }}"
    environment: "{{ .Values.environment }}"
    version: "{{ .Values.version }}"
type: Opaque
stringData:
  client-id: "Ov23lilIgBRlv4NlnUli"
  client-secret: "5d4f1759fa2200dbfa34f1a4357d26c7b399fc11"