apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: <TUNNEL-ID>
    credentials-file: /etc/cloudflared/credentials.json
    ingress:
      - service: http://istio-ingressgateway.istio-system.svc.cluster.local:80