apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: 28bbc94f-411d-4c67-9399-2cfce007e206
    credentials-file: /etc/cloudflared/credentials.json
    ingress:
      - service: http://istio-ingressgateway.istio-system.svc.cluster.local:80