apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: <TUNNEL-ID>
    credentials-file: /etc/cloudflared/credentials.json
    ingress:
      - hostname: argocd.ncostamagna.com
        service: https://argocd-server.argocd.svc.cluster.local:443
        originRequest:
          noTLSVerify: true
      - hostname: passit.ncostamagna.com
        service: http://passit-front.default.svc.cluster.local:80
      - service: http_status:404
