replicaCount: 1
version: 1
name: ecommerce-back
environment: development

deployment:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  image:
    url: ncostamagna/ecommerce-back
    version: "877c659b21025749c9d1e4d0c51c914133ae0588"
    pullPolicy: IfNotPresent

  api:
    http:
      targetPort: 8020
      nodePort: 30009
secrets:
  database:
    url:
      name: ecommerce-back-db
      key: url
  redis:
    addr:
      name: ecommerce-back-redis
      key: addr
    password:
      name: ecommerce-back-redis
      key: password
config:
  app:
    port: 8020
    env: development

  database:
    url: postgres://ecommerce:ecommerce@localhost:5442/ecommerce?sslmode=disable

  redis:
    db: 3

  jwt:
    secret: supersecretkey
    expiry_hours: 24

  resend:
    api_key: re_MAEg8pdk_8K9asa6NMhYH9ajkbxDj2cpU

  s3:
    bucket: ecommerce
    public_url: http://localhost:4566/ecommerce
    region: us-east-1
    endpoint: http://localhost:4566
    access_key_id: test
    secret_access_key: test


# DELETE ALL
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: passit-back.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
