replicaCount: 1
version: 1
name: passit-back
environment: development

deployment:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  image:
    url: ncostamagna/passit-back
    version: "8b7b76048ee64256134d121ac3031a21e28b8cec"
    pullPolicy: IfNotPresent

  api:
    grpc:
      targetPort: 8080
      nodePort: 30003

config:
  api:
    grpc:
      host: localhost
      port: 8050

  redis:
    addr: localhost:6381
    pass: admin
    db: 3

  token: my-token


# DELETE ALL
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: passit-back.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
