replicaCount: 1
version: 1
name: ecommerce-bo-front
environment: development

deployment:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  image:
    url: ncostamagna/ecommerce-bo-front
    version: "62d76f63b8ff9d42396ffe5ee9c98739288b9524"
    pullPolicy: IfNotPresent
  serviceType: ClusterIP

config:
  port: 3000
  baseUrl: "https://ecommerce-bo.ncostamagna.com"
  backendUrl: "http://ecommerce-back.lapaltech.svc.cluster.local:8020"

gateway:
  host: "ecommerce-bo.ncostamagna.com"

